> file.choose() # [1] "/home/skrgovic/bmw_m6_by_roof01-d4cawmj.jpg" -> olute path name
# Deliverables / Calc Exercises -> relative path name

#There are two types of basic objects: Strings and Digits

#More complex objects: arrays (vectors) 1:500, or c("hello", "Charlie")
#Arrays are homogenous, collections of the same kinds of things
paste("hello", 1:20)
paste("hello", 1:20, sep= "-", collapse= "*") #one string, because of collapse
list("hello", 1) #heterogenous

#Another complex object: dataframe

myframe = data.frame( a=1:5, letters=c("a","b","c","d","e"))

complicated <- "The fog comes in\non little cats feet"   #\n is a new line
complicated
cat(complicated)

# \ escape character

cat("\"I dont want to go to the doctor\" , said Billy to Mommy")
cat("Remember to escape the \ with \\")
cat("Remember to escape the \\ with \\\\")


# Strings, Numbers and collections
Funny things happen when you construct strings.
Things like cat("\") indicate "control characters".

```{r}

"God.damn.it"
